### ISSUE TITLE
DetailProduct View 로직에 관해서

### ISSUE THREAD

**Issue by dyjung123** [next-ivis/niShopping#27]
개요
- 임의의 상품 1개에 대한 세부 정보를 보기 위해서 어떤 임의의 View에서 DetailProduct View로 이동하는 상황에서의 로직을 구성. 

전제
- vuex state에 productInfo를 가져오는것은 비효율적이라 판단하여 DetailProduct 내부의 Data, Prop을 이용함.
- axios를 사용한 api 호출은 vuex의 Actions에서 하며 DetailProduct는 mapAction을 import하여 이를 호출하려 하는데 productInfo는 app state가 아니므로 이런 형태는 부적절한지에 대해서 **의견 필요**
- 단 **하나의 상품 정보**만이 필요하므로 product의 기본키(productId)를 DetailProduct에서 api 호출 메서드에 매개변수로 던져줌.
- DetailProduct.vue에서 Prop인 productId (상품코드)와 Data인 productInfo (단일 상품 정보)사용.

현재 구상 로직
**->**  임의의 이전 view에서 product가 전시되어 있는 card 클릭
-> DetailProduct View의 productId (Prop)으로 router param를 통해서 상품 코드(productId)를 전송
-> productId (Prop)가 변경시 실행되는 getProductInfo 메서드 호출
-> getProductInfo가 productId (Prop)를 넘기면서 mapAction의 getProduct() 메서드를 호출
-> getProduct(productId)는 apiService의 defaultGet 호출
-> 반환 받은 해당 상품 정보를 productInfo (Data)에 할당, DetailProduct View에서 표시

고려 한 사항( 해결 완료 )
1. 만약 DetailView.vue가 destroy되지 않고 상품 코드만 바뀌는 경우가 있을 수 있음.
2. mouted 시점까지 productInfo를 받아오지 못할 경우 상품 정보가 렌더링 되지 않음.
 2 - 1. 단순 지연일 경우에 {{ }} (mustache)에서 변경을 감지하고 렌더링을 해주는가?
    -> default Value 없는 undefined의 경우 안되므로 productInfo (Data)의 default Value 필요.
 2 - 2. 로딩 실패일 경우를 대비해서 productInfo의 default Value가 필요.

해결 
- productId (Prop)에 Watch를 걸어놓고 immediate option을 true로 설정
- productInfo (Data)의 타입은 Union ( productType | object ), 빈 객체 {}로 초기화.

**Comment by DohwanKim** [comment]
님 근데 detailproduct 부터 올려주셈.

**Comment by deokgoo** [comment]
해결 된거임? ㅇㅅㅇ 해결된거면 닫아주삼

**Comment by dyjung123** [comment]
로그인체크 필요한가,
mapAction 통한 api 호출은 vuex state가 아니니까 필요없는것 같고
